### PR TITLE
Add pdftopng and use ghostscript as fallback

### PR DESCRIPTION
**Pull request by vinayak-mehta**
Raised this PR just to run tests. This change would have to be handled in a backwards compatible way by adding support for multiple image conversion backends which the user could specify (`ghostscript`, `mupdf`, etc.), and setting `pdftopng` as the default one.

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
Yay most tests pass! :tada:

The ones that failed have image coordinates hardcoded, they will have to be changed.

**Comment by arky** [comment]
@vinayak-mehta Let me know if further testing is needed on this PR or any task the needs to be done to move this forward. Thanks

**Comment by vinayak-mehta** [comment]
Just need to add tests now.

**Comment by vinayak-mehta** [comment]
It's just failing on macOS :(

**Comment by vinayak-mehta** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
