### PR TITLE
[MRG] Fixed ZeroDivisionError in text_in_bbox

### PR DESCRIPTION
**Pull request by const-FC**
Fixing https://github.com/camelot-dev/camelot/issues/260

### CODE REVIEW

**Review by bosd — APPROVED** [review]
Code review LGTM

**Comment by bosd** [comment]
fixes #335

**Review by molhineko — APPROVED** [review]

**Comment by MartinThoma** [comment]
Hey!

As [camelot is dead](https://github.com/camelot-dev/camelot/issues/343), we try to build a maintained fork at [`pypdf_table_extraction`](https://github.com/py-pdf/pypdf_table_extraction).

Do you want to open the PR against that branch so that we can merge your improvement?

**Comment by bosd** [comment]
Thanks for your contribution. This has been merged in adifferent pr.

**Pull request closed without merging**
