### PR TITLE
 Fix notebook link

### PR DESCRIPTION
**Pull request by bosd**

### CODE REVIEW

**Review by vinayak-mehta — APPROVED** [review]
Sorry completely missed that!

**Comment by vinayak-mehta** [comment]
Thanks for fixing these 🙏🏽

**Comment by bosd** [comment]
This pr at least fixes the borken links.
But the notebooks itself needs some work as well. As the still reference the `pypdf_table_extraction` name
image

**Comment by vinayak-mehta** [comment]
I can update the notebook after making a new release. Do you think there are any other things left before publishing a release?

**Comment by bosd** [comment]
I just noticed the [release](https://github.com/camelot-dev/camelot/releases) drafter does not seem to be working.
( I do not have enough powers here.)

image
image


Maybe make the next release also a major release.
I deprecated ghostscript is a main dependency. Because of license, and people having sometimes difficulty installing it.

So this section might need updating as well.
image


With poetry I had some troubles with the versioning. As it was defined in the version file as well as in the toml. And it did'nt sync automatically. (The poetry bump version plugin ws not working for me as well.)
I think that now we switchted to uv. The version file is no longer needed.

**Comment by vinayak-mehta** [comment]
Let me go through all of that. Did you receive an organization invite? I'd invited you as a member but it still shows you as an outside collaborator. 
image

**Comment by bosd** [comment]
> Let me go through all of that. Did you receive an organization invite? I'd invited you as a member but it still shows you as an outside collaborator. Ooh, just noticed I recevied a second email as well. Just clicked on that link. I'm in the org now. But it does not seem to change my permissions.

**Comment by vinayak-mehta** [comment]
Should we merge this PR and continue the conversation here? https://github.com/camelot-dev/camelot/issues/518

I'll draft a release locally instead of using the github action for now

**Comment by bosd** [comment]
> Should we merge this PR and continue the conversation here?

Good plan!

**Comment by vinayak-mehta** [comment]
@bosd do you want to go ahead and merge it?

**Comment by bosd** [comment]
It seems like the upload to readthedocs is broken. Because there is till serves us the old version.

**Comment by vinayak-mehta** [comment]
Fixed it, latest docs should be pushed soon

**Pull request merged**
