### PR TITLE
Fix notebook link

### PR DESCRIPTION
**Pull request by vinayak-mehta**

### CODE REVIEW

**Comment by bosd** [comment]
fyi, notebook link is still broken

**Comment by vinayak-mehta** [comment]
let me check

**Comment by vinayak-mehta** [comment]
both links open for me from the github readme and readthedocs, are there other notebook links somewhere in the docs?

**Comment by bosd** [comment]
fix in #517 

The "code fix" in this commit is not working for me.
Before: (quickly taken from other repo.)
image

here:
image

**Comment by vinayak-mehta** [comment]
Let me check

**Comment by bosd** [comment]
There is more, these ones need upadting as well.
https://github.com/camelot-dev/camelot/blob/master/docs/user/how-it-works.rst

**Pull request merged**
