### PR TITLE
[WIP] Add support for parsing PDF pages in parallel

### LINKED ISSUE #20: Use multiprocessing to parallely process PDF pages
<pre>
>>> camelot.read_pdf('filename.pdf', pages='all', parallel=True)
</pre>

We could try and use all cores present on the machine using multiprocessing. More ideas are welcome.

### PR DESCRIPTION
**Pull request by phoewass**
Closes #20 

Parse pages in parallel using multiprocessing library leveraging all the available CPUs.

**Checklist:**
- [x]  Process in parallel using the library
- [x] Tests to process with and without parallel option
- [ ] Process in parallel using the CLI
- [ ] Update documentation

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
Why do we need to pass `parallel` as an argument to each test?

**Comment by phoewass** [comment]
I did this to avoid copying the tests and make sure that the new argument `parallel` does not break the API.

**Comment by maxdd** [comment]
Will this ever be merged?

**Comment by jgcmarins** [comment]
What is missing for this to be merged?

**Comment by hashangayasri** [comment]
Is this still WIP? What's preventing this from being merged?

**Comment by MartinThoma** [comment]
Currently, there are merge conflicts that first need to be resolved.

https://github.com/camelot-dev/camelot/pull/353 might also get merged and that makes me uncertain how to continue with all others

**Comment by MartinThoma** [comment]
Hey!

As [camelot is dead](https://github.com/camelot-dev/camelot/issues/343), we try to build a maintained fork at [`pypdf_table_extraction`](https://github.com/py-pdf/pypdf_table_extraction).

Do you want to open the PR against that branch so that we can merge your improvement?

**Comment by phoewass** [comment]
Moved to https://github.com/py-pdf/pypdf_table_extraction/pull/17

**Pull request closed without merging**
