### PR TITLE
Sync with fork

### PR DESCRIPTION
**Pull request by vinayak-mehta**

### CODE REVIEW

**Comment by bosd** [comment]
@vinayak-mehta so is it your plan now to bring this back into this repo?

**Comment by vinayak-mehta** [comment]
Yeah I don't want this project to fragment, which is why I created and invited everyone to this organization in the first place

I'll work on reverting some of the naming stuff etc. and get this merged as soon as I can

**Comment by vinayak-mehta** [comment]
Created a new PR https://github.com/camelot-dev/camelot/pull/514

**Comment by bosd** [comment]
> Yeah I don't want this project to fragment,

Afaik that already happened long ago.
Can you please fix the issue with the 2 Camelot repos and organizations?
The socialdev / Atlantahq is found by Camelot users.

(At least it is clear by the new name that pypdf_table_extraction is the successor of Camelot.)


>which is why I created and invited everyone to this organization in the first place

Well, welcome back after 2 years. 🎉 sadly we didn't have enough permissions to continue development and the organization here.

> I'll work on reverting some of the naming stuff etc. and get this merged as soon as I can.

Do you plan on continue the development and follow up on issues here? 

( How about the other projects? Excalibur and pdf2image)

**Comment by vinayak-mehta** [comment]
> Can you please fix the issue with the 2 Camelot repos and organizations?

Sadly, that one is out of my control

> Well, welcome back after 2 years. 🎉 sadly we didn't have enough permissions to continue development and the organization here.

Sorry I thought you all already had all the permissions, I added Martin on the PyPI project too

> Do you plan on continue the development and follow up on issues here? (How about the other projects? Excalibur and pdf2image)

Yes, I just pushed a new version for excalibur and new wheels for pdftopng

**Comment by bosd** [comment]
Oh cool,
I didn't work on Excalibur. I tried the tool, but encountered a lot of Issues.

At a moment I was thinking to better abandon it. Because similar debugging functionality can be done now in the notebooks. And it just adds to the maintenance workload.

Maybe open up a organization discussion somewhere with the others. So we can prevent the key person risk and slipping this into abandonware again.

**Comment by bosd** [comment]
@vinayak-mehta 
The situation with the atlantahq / socialdev old repo is utterly confusing.
Did you contact github support to explain your situation?
Maybe they can point it to the camelot-dev one.
Or at least mark it as "Public Archive".

Do you have any powers there? Maybe you can open a PR to point people to the correct repo.

**Comment by vinayak-mehta** [comment]
I know it's a pain 😭 

I haven't tried to contact github support or open a PR in the main org yet.

I can talk you through the reasoning behind this repo existing by itself on email perhaps to discuss what's the best way forward. I don't see your email, you can send me one (my email is in the git log) if that works for you.

**Pull request closed without merging**
