### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by MartinThoma**
* Update the version to `(0, 20, 1)`
* Use [flit](https://flit.pypa.io/en/latest/index.html) for uploading packages to PyPI
* Add a `Makefile` as this is probably easiest to discover / understand for anybody how the package building and uploading works

### CODE REVIEW

**Comment by foarsitter** [comment]
Can you elaborate a little more on your design choices? 

Why did you introduced a second package manager and why are all the dependencies listed twice in pyproject.toml?

**Comment by MartinThoma** [comment]
flit is not a package manager. It's simply a tool to build and upload a package to PyPI.

I'm using flit already in other projects and I like that it uses the standard (PEP 621). I don't like poetry because it introduces its own format and seems bloated to me. Also it is a pain to check the updates of a poetry lockfile (in contrast to pip-compile created requirements.txt files).

https://github.com/python-poetry/poetry/issues/3332 is about poetry following the standard. I don't think that is happening soon.

**Comment by foarsitter** [comment]
I don't see what problems being solved here by adding flit. On the long term one may argue that Poetry needs to replaced in its whole because it doesn't follow the standards. Adding a new tool to do a task that is already taking care of doesn't make sense to me.

**Comment by marcozzxx810** [comment]
I think we are able to publish through poetry build and poetry publish.

May I know What problem we are solving for this PR?

**Pull request closed without merging**
